### ISSUE TITLE
Add utc-check for campaigns.all time fields

### ISSUE THREAD

**Issue by AnnaDamm** [VingtCinq/python-mailchimp#133]
I found out the hard way, that the timezone in the fields before_create_time, since_create_time, before_send_time, since_send_time in the campaigns list view have to be UTC.

You can test this by creating a campaign and then using since_create_time with e.g '+01:00' timezone. 
The endpoint ignores the timezone and just checks for the datetime itself in UTC, so it will not find the campaign.

So, the same as it is done in campaigns.actions.schedule, those fields should be added as datetime objects and then a UTC-check could be added.

**Comment by stephenross** [comment]
Our API does not process queryparams arguments at all, as that is expected to be processed be the end user beforehand. We perform processing on any actual post data sent through as those will cause hard errors, but logic errors caused by incorrect queryparams do not technically cause the API to malfunction, it simply returns unexpected results. My plan is to simply update the docstring wherever those queryparams are indicated (which I believe is more endpoints that simply campaigns.all()). If there is dissenting opinion from the other maintainers, we will look into a different solution as needed.
