### ISSUE TITLE
 API Error Handling Solutions For 429 Level Errors

### ISSUE THREAD

**Issue by MadPy81** [VingtCinq/python-mailchimp#194]
Hello, 

**Background:** 
I'm pulling data from Mailchimp API and writing data into Google Sheets via sheets API. Essentially, my script makes an initial req for all current campaign data to extract "campaign id" which I then use in a subsequent function to run the 2nd request for 'click_details' reports. I then write the data into the Google Sheet. I'm new to writing these programs/scripts.

I'm being throttled by Google Sheets API. Specifically for exceeding "Write requests per 100 seconds per user". 

**Error Received:**
`gspread.exceptions.APIError: {
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota group 'WriteGroup' and limit 'USER-100s' of service 'sheets.googleapis.com' for consumer 'project_number:30XXXXX'.",
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
`

**Question to community:**
I'm actively looking through my code for ways to consolidate or reduce operations. However, is there a way to space out(back off) request frequency by checking for a status code of "429". in the code?

**Code:** ( see attached image) I couldn't figure out how to include here without being messy.
<img width="902" alt="code" src="https://user-images.githubusercontent.com/9815044/57637830-5be98000-757a-11e9-9e7b-983504293dfb.png">

Thanks for any help or insight in advance. 

`

**Comment by stephenross** [comment]
Hi @MadPy81, This is the issues for the MailChimp API wrapper, but it sounds like you are having an issue with the wrapper for Google Sheets. You might want to try looking over the Sheets documentation for information. You might also want to try building the data structure for your sheet locally and pushing larger chunks of data if that is an option (push whole sets of rows instead of 1 at a time for example).
