### ISSUE TITLE
Error to try creating a list

### ISSUE THREAD

**Issue by diegocastroplazas** [VingtCinq/python-mailchimp#197]
Hi Guys!

I've been using your python module for sending campaigns since 1 year ago and it had been working very well. However since a few days ago, we're obtaining the error as following.

`mailchimp3.mailchimpclient.MailChimpError: {'type': 'http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/', 'title': 'User action not permitted', 'status': 403, 'detail': 'User does not have access to the requested operation', 'instance': '6504625c-e316-4a96-bedf-af444621979b'}`

I've checked the permissions for the API Key and it's ok because this user is the only admin. I would like to know if somebody has experimented this error before.

Let me know if you need further details. Thanks

**Comment by stephenross** [comment]
No idea if you are still seeing that error, but I will ask some questions just in case. Does your MailChimp account have any restrictions on it? Check for any problems in the Account Issues section of your account page. Additionally, what is the specific action you are attempting when you receive that error? If you are not seeing this issue any longer, please close this issue.

Thanks
Stephen Ross II

**Comment by smajkows** [comment]
I've also experienced this error and I have created an API key and am the owner of the mailchimp account I'm using this on. 

For reference I have been able to successfully read and write data from lists using this library but creating a list is throwing a 403 error for me as well.

**Comment by stephenross** [comment]
If you are getting a 403 error, you likely do not have any allowance for any additional lists. The lower tier plans allow a limited number of lists, with the free plan only allowing 1, and hiding a lot of the information about that list because you don't have access to some of the interface surrounding it. For reference, List in the api documentation and the package is the same as the Audience terminology more recently used by MailChimp.
