### ISSUE TITLE
Feature Request: Asynchronous calls

### ISSUE THREAD

**Issue by dzbee** [VingtCinq/python-mailchimp#198]
I am using this package to create, update, and tag users according to interactions they take with my web app. Since there is (as far as I can tell) no support for making asynchronous calls to the API outside of MailChimp's own batch jobs, users must wait for the API call to complete on the backend before receiving a response to their request. While I could use batch jobs for this purpose, this requires me to follow up with queries to the API later on if I want to catch and log any errors. I'd like to request support for asynchronous calls such as `client.lists.members.create_or_update(..., async=True)`. If there is a rationale for not supporting such calls I'd also be interested to hear it.

**Comment by stephenross** [comment]
If I am reading this correctly, you are adding and updating list members using this package and would like a method to do so asynchronously so that you can simply trigger the request without waiting or checking the return? I would be interested to hear your use case for why you would not want to wait for the return of those calls so that you can handle any errors that might come back. Currently, this package attempts to be as lightweight as possible, with only some very select additional features for ease of use included at this time such as providing a tool to automatically calculate subscriber hashes and the like.

It sounds like for your web app, a package such as celery for processing these requests asynchronously would be a more robust fit than anything that might be added directly to this package, and is how I personally have done pretty much exactly what you are asking about, which allows me to have the workers process the requests without blocking execution of the main thread, while still allowing me to receive the response in a blocking manner on the worker thread so that I can process the response for any errors or data I may want to save. In my use case, I have functionality that allows updating a subscriber's email address, and when MailChimp returns the updated object, the subscriber hash has updated, so I persist that back to my DB, but I have also made sure that the main thread that calls the task is not altering that DB record after making the request so that I don't have any race conditions related to the record updates.

If you are still having issues with this, let us know.

**Comment by dzbee** [comment]
The case you describe with celery is along the lines of what I wanted. Thanks, I'll check it out.
