### ISSUE TITLE
Missing "get_all" implementation within listactivity entity

### ISSUE THREAD

**Issue by nikey5** [VingtCinq/python-mailchimp#209]
Currently it is not possible to retrieve all the existing data of the listactivity by iterating through all existing data points. However, other entities have implemented the "get_all" functionality. Can this also be implemented within the listactivity? 
I tested the same functionality within the listactivity locally and it worked fine.
Thank you for your help!

**Comment by stephenross** [comment]
The allowed queryparams for the listactivity endpoint do not include the count and offset fields required to implement a get_all call, which is why it was not included. See https://mailchimp.com/developer/reference/lists/list-activity/ for the allowed query params. If you think there is a missing parameter and that count and offset are allowed, please contact the MailChimp API support and ask them to update the documentation. Once the documentation on the MailChimp side has been corrected, please submit a PR following the existing formats for a get_all kwarg and we will review it.
